package mthiebi.sgs.gradebook.service;

import mthiebi.sgs.SGSException;
import mthiebi.sgs.SGSExceptionCode;
import mthiebi.sgs.gradebook.engine.CellKey;
import mthiebi.sgs.gradebook.engine.CellValue;
import mthiebi.sgs.gradebook.engine.ComponentDef;
import mthiebi.sgs.gradebook.engine.EvalOutcome;
import mthiebi.sgs.gradebook.engine.EvaluationContext;
import mthiebi.sgs.gradebook.engine.Evaluator;
import mthiebi.sgs.gradebook.engine.PeriodReach;
import mthiebi.sgs.gradebook.engine.PeriodTree;
import mthiebi.sgs.gradebook.engine.TemplateGraph;
import mthiebi.sgs.gradebook.engine.WorkingSet;
import mthiebi.sgs.gradebook.model.Enrollment;
import mthiebi.sgs.gradebook.model.GradeEntry;
import mthiebi.sgs.gradebook.repository.EnrollmentRepository;
import mthiebi.sgs.gradebook.repository.GradeEntryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Answers "why does this cell say what it says".
 * <p>
 * The working is produced by the same evaluate() call that computes the value,
 * in trace mode. Not a second implementation: an explanation generated by
 * separate code drifts from the calculation and is believed anyway.
 * <p>
 * Nothing is stored. It is recomputed on request, so it cannot go stale against
 * the value it explains.
 */
@Service
public class GradeExplainService {

    @Autowired
    private EnrollmentRepository enrollmentRepository;

    @Autowired
    private GradeEntryRepository gradeEntryRepository;

    @Autowired
    private TemplateVersionResolver templateVersionResolver;

    @Autowired
    private TemplateGraphLoader templateGraphLoader;

    @Autowired
    private PeriodTreeLoader periodTreeLoader;

    @Autowired
    private SpecialValueRegistry specialValueRegistry;

    private final Evaluator evaluator = new Evaluator();

    @PersistenceContext
    private EntityManager em;

    @Transactional(readOnly = true)
    public GradeExplanation explain(Long enrollmentId, Long subjectId, Long periodId,
                                    String componentCode, String journalUuid)
            throws SGSException {

        Enrollment enrollment = enrollmentRepository.findById(enrollmentId)
                .orElseThrow(() -> new SGSException(SGSExceptionCode.BAD_REQUEST,
                        "ჩარიცხვა ვერ მოიძებნა"));

        mthiebi.sgs.gradebook.model.GradingTemplate journal =
                templateVersionResolver.journalByUuid(journalUuid);
        Long versionId = templateVersionResolver
                .resolve(enrollment.getClassGroup().getId(), subjectId, periodId, journal.getId())
                .getVersion().getId();

        TemplateGraph graph = templateGraphLoader.graphOf(versionId);
        ComponentDef component = graph.byCode(componentCode);
        if (component == null) {
            throw new SGSException(SGSExceptionCode.BAD_REQUEST, "უცნობი სვეტი: " + componentCode);
        }
        if (!component.isDerived()) {
            throw new SGSException(SGSExceptionCode.BAD_REQUEST,
                    "სვეტი " + componentCode + " ხელით შეიყვანება და არ გამოითვლება");
        }

        PeriodTree periods = periodTreeLoader.treeOf(
                enrollment.getClassGroup().getPeriodScheme().getId());

        // The same set the write path loads, from the same place.
        //
        // It used to be a near-copy: self, children, ancestors, and the SPECIFIC
        // periods. "Near" was the problem. When DESCENDANTS arrived only the
        // write path was taught it, so explaining a yearly total loaded none of
        // the periods it actually sums and reported every source EMPTY - an
        // explanation that contradicted the number it was explaining, which is
        // worse than no explanation at all.
        Set<Long> periodIds = new LinkedHashSet<>(
                PeriodReach.of(periods).workingSet(periodId, graph));

        List<Long> enrollmentIds = java.util.Collections.singletonList(enrollmentId);
        Map<CellKey, CellValue> cells = new HashMap<>();
        for (GradeEntry entry : gradeEntryRepository.loadGrid(
                enrollmentIds, new ArrayList<>(periodIds), subjectId)) {
            cells.put(keyOf(entry), toCellValue(entry));
        }
        if (!component.isSubjectScoped()) {
            for (GradeEntry entry : gradeEntryRepository.loadComponentsAcrossSubjects(
                    enrollmentIds, new ArrayList<>(periodIds),
                    component.getRule().allSourceComponentIds())) {
                cells.putIfAbsent(keyOf(entry), toCellValue(entry));
            }
        }

        EvaluationContext ctx = new EvaluationContext(graph, periods, new WorkingSet(cells),
                subjectIdsOf(enrollment.getClassGroup().getId()),
                specialValueRegistry.behavioursFor(versionId));
        ctx.setJournalDepth(journal.getFrequency().getDepth());

        CellKey key = new CellKey(enrollmentId,
                component.isSubjectScoped() ? subjectId : null, periodId, component.getId());

        EvalOutcome outcome = evaluator.evaluate(key, component, ctx, true);
        return new GradeExplanation(componentCode, component.getLabel(),
                outcome.getValue(), outcome.getTrace());
    }

    private List<Long> subjectIdsOf(Long classGroupId) {
        return em.createQuery(
                        "select cs.subject.id from ClassSubject cs where cs.classGroup.id = :id "
                                + "order by cs.sortIndex", Long.class)
                .setParameter("id", classGroupId).getResultList();
    }

    private CellKey keyOf(GradeEntry entry) {
        return new CellKey(entry.getEnrollment().getId(),
                entry.getSubject() == null ? null : entry.getSubject().getId(),
                entry.getPeriod().getId(), entry.getComponent().getId());
    }

    private CellValue toCellValue(GradeEntry entry) {
        return new CellValue(entry.getValue(), entry.getSpecialValue(), entry.getSource(),
                entry.isOverride(), entry.getRowVersion());
    }
}
