spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SGS;
    username: frtadmin
    password: admin
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: testforsmtp6@gmail.com
    password: avncxlaclvgqtdhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            todo: need to create new email for Mtiebi and generate app password
jwt:
  secret: secretkey123