spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SGS;
    username: sa
    password: SGSadmin2023
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ibmthiebi.student.rating@gmail.com
    password: yehzoetipbbvqhuq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: secretkey123