spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SGS;
    username: sa
    password: Mfcatl007
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: secretkey123