import React from "react";
import {useQuery} from "react-query";
import {Divider, Drawer, IconButton, Typography} from "@mui/material";
import {Close} from "@mui/icons-material";
import {explainCell} from "./gradebookApi";

/**
 * Why a calculated cell holds the value it does.
 *
 * The working comes from the same evaluate() call that produced the number, run
 * in trace mode. Not a second implementation: an explanation generated by
 * separate code drifts from the calculation and is believed anyway.
 */
const ExplainPanel = ({target, subjectId, periodId, journalUuid, onClose}) => {

    const {data, isLoading, isError} = useQuery(
        ["GRADE_EXPLAIN", target?.enrollmentId, target?.componentCode, subjectId, periodId,
            journalUuid],
        () => explainCell({
            enrollmentId: target.enrollmentId,
            subjectId,
            periodId,
            componentCode: target.componentCode,
            journalUuid
        }),
        {enabled: Boolean(target), refetchOnWindowFocus: false}
    );

    return (
        <Drawer anchor="right" open={Boolean(target)} onClose={onClose}>
            <div style={{width: 420, padding: 20}}>
                <div style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
                    <Typography variant="h6">{data?.componentLabel || "გამოთვლა"}</Typography>
                    <IconButton size="small" onClick={onClose}><Close/></IconButton>
                </div>

                {target ? (
                    <Typography variant="body2" style={{color: "#666", marginBottom: 12}}>
                        {`${target.lastName} ${target.firstName}`}
                    </Typography>
                ) : null}

                <Divider style={{marginBottom: 16}}/>

                {isLoading ? <Typography variant="body2">იტვირთება…</Typography> : null}
                {isError ? (
                    <Typography variant="body2" style={{color: "#a94442"}}>
                        ამ უჯრის გამოთვლის ახსნა ვერ მოხერხდა
                    </Typography>
                ) : null}

                {data ? (
                    <>
                        <Typography variant="h4" style={{marginBottom: 16}}>
                            {data.value ?? "—"}
                        </Typography>

                        {(data.trace?.terms || []).map((term, i) => (
                            <div key={i} style={{marginBottom: 14}}>
                                <Typography variant="subtitle2">
                                    {term.label || `წევრი ${i + 1}`}
                                    {term.weight != null
                                        ? ` — ${(Number(term.weight) * 100).toFixed(0)}%`
                                        : ""}
                                </Typography>

                                {(term.sources || []).map((source, j) => (
                                    <div key={j} style={{
                                        display: "flex", justifyContent: "space-between",
                                        fontSize: 13,
                                        color: source.status === "USED" ? "#333" : "#999",
                                        paddingLeft: 10
                                    }}>
                                        <span>
                                            {source.componentCode}
                                            {source.status === "USED"
                                                ? ""
                                                : ` (${statusLabel(source.status)})`}
                                        </span>
                                        <span>
                                            {source.specialValue ?? source.value ?? "—"}
                                        </span>
                                    </div>
                                ))}

                                {term.reduced != null ? (
                                    <div style={{
                                        display: "flex", justifyContent: "space-between",
                                        fontSize: 13, fontWeight: 600, paddingLeft: 10, marginTop: 4
                                    }}>
                                        <span>შედეგი</span><span>{term.reduced}</span>
                                    </div>
                                ) : null}
                            </div>
                        ))}

                        <Divider style={{margin: "12px 0"}}/>

                        {/* Rounding happens once, on the final value, so the raw
                            figure is worth showing when it differs. */}
                        {data.trace?.raw != null
                        && String(data.trace.raw) !== String(data.trace.value) ? (
                            <Typography variant="caption" style={{display: "block", color: "#666"}}>
                                {`დაუმრგვალებელი: ${data.trace.raw} → ${data.trace.decimals} ათწილადამდე`}
                            </Typography>
                        ) : null}

                        {data.trace?.usedFallback ? (
                            <Typography variant="caption" style={{display: "block", color: "#8a6d3b"}}>
                                გამოყენებულია სათადარიგო წესი.
                            </Typography>
                        ) : null}
                    </>
                ) : null}
            </div>
        </Drawer>
    );
};

const statusLabel = (status) => {
    switch (status) {
        case "EMPTY":
            return "არ არის შეყვანილი";
        case "SPECIAL_EXCLUDED":
            return "არ ითვლება";
        case "SPECIAL_AS_ZERO":
            return "ითვლება როგორც 0";
        case "BLOCKED":
            return "ბლოკავს გამოთვლას";
        default:
            return status;
    }
};

export default ExplainPanel;
