package mthiebi.sgs.models;

public enum GradeType {

    // აკადემიური შეფასებების ცხრილი საგნების მიხედვით:
    SUMMARY_ASSIGMENT_1,
    SUMMARY_ASSIGMENT_2,
    SUMMARY_ASSIGMENT_RESTORATION,
    SUMMARY_ASSIGMENT_MONTH,
    SUMMARY_ASSIGMENT_PERCENT,

    HOMEWORK_WRITE_ASSIGMENT,
    HOMEWORK_CREATIVE_ASSIGMENT,
    HOMEWORK_SUM_1,
    HOMEWORK_SUM_2,

    SCHOOL_WORK_1,
    SCHOOL_WORK_MONTH,
    SCHOOL_WORK_PERCENT,

    COMPONENT_1,
    COMPONENT_2,
    COMPONENT_3,

    // ეთიკური ნორმების შეფასებების ცხრილი:
    APPEARING_IN_UNIFORM_1,
    APPEARING_IN_UNIFORM_2,
    APPEARING_IN_UNIFORM_3,
    APPEARING_IN_UNIFORM_4,
    APPEARING_IN_UNIFORM_5,
    APPEARING_IN_UNIFORM_GRADE,

    STUDENT_DELAYS_1,
    STUDENT_DELAYS_2,
    STUDENT_DELAYS_3,
    STUDENT_DELAYS_4,
    STUDENT_DELAYS_5,
    STUDENT_DELAYS_GRADE,

    CLASSROOM_INVENTORY_1,
    CLASSROOM_INVENTORY_2,
    CLASSROOM_INVENTORY_3,
    CLASSROOM_INVENTORY_4,
    CLASSROOM_INVENTORY_5,
    CLASSROOM_INVENTORY_GRADE,

    STUDENT_HYGIENE_1,
    STUDENT_HYGIENE_2,
    STUDENT_HYGIENE_3,
    STUDENT_HYGIENE_4,
    STUDENT_HYGIENE_5,
    STUDENT_HYGIENE_GRADE,

    STUDENT_BEHAVIOR_1,
    STUDENT_BEHAVIOR_2,
    STUDENT_BEHAVIOR_3,
    STUDENT_BEHAVIOR_4,
    STUDENT_BEHAVIOR_5,
    STUDENT_BEHAVIOR_GRADE,

    // გაცდენილი საათების ცხრილი:
    MONTHLY,

    // ტრანზიტული სკოლა:
    TRANSIT_SUMMARY_ASSIGMENT_1,
    TRANSIT_SUMMARY_ASSIGMENT_2,
    TRANSIT_SUMMARY_ASSIGMENT_RESTORATION,
    TRANSIT_SUMMARY_ASSIGMENT_MONTH,

    TRANSIT_SCHOOL_WORK_1,
    TRANSIT_SCHOOL_WORK_2,
    TRANSIT_SCHOOL_WORK_3,
    TRANSIT_SCHOOL_WORK_MONTH

}
