package mthiebi.sgs.models;

public enum GradeType {

    // აკადემიური შეფასებების ცხრილი საგნების მიხედვით:
    GENERAL_SUMMARY_ASSIGMENT_1,
    GENERAL_SUMMARY_ASSIGMENT_2,
    GENERAL_SUMMARY_ASSIGMENT_RESTORATION,
    GENERAL_SUMMARY_ASSIGMENT_MONTH,
    GENERAL_SUMMARY_ASSIGMENT_PERCENT,
    GENERAL_HOMEWORK_WRITE_ASSIGMENT,
    GENERAL_HOMEWORK_CREATIVE_ASSIGMENT,
    GENERAL_HOMEWORK_SUM_1,
    GENERAL_HOMEWORK_SUM_2,
    GENERAL_SCHOOL_WORK_1,
    GENERAL_SCHOOL_WORK_MONTH,
    GENERAL_SCHOOL_WORK_PERCENT,
    GENERAL_COMPONENT_1,
    GENERAL_COMPONENT_2,
    GENERAL_COMPONENT_3,
    GENERAL_COMPLETE_MONTHLY,

    // ეთიკური ნორმების შეფასებების ცხრილი:
    BEHAVIOUR_APPEARING_IN_UNIFORM_1,
    BEHAVIOUR_APPEARING_IN_UNIFORM_2,
    BEHAVIOUR_APPEARING_IN_UNIFORM_3,
    BEHAVIOUR_APPEARING_IN_UNIFORM_4,
    BEHAVIOUR_APPEARING_IN_UNIFORM_5,
    BEHAVIOUR_APPEARING_IN_UNIFORM_GRADE,

    BEHAVIOUR_STUDENT_DELAYS_1,
    BEHAVIOUR_STUDENT_DELAYS_2,
    BEHAVIOUR_STUDENT_DELAYS_3,
    BEHAVIOUR_STUDENT_DELAYS_4,
    BEHAVIOUR_STUDENT_DELAYS_5,
    BEHAVIOUR_STUDENT_DELAYS_GRADE,

    BEHAVIOUR_CLASSROOM_INVENTORY_1,
    BEHAVIOUR_CLASSROOM_INVENTORY_2,
    BEHAVIOUR_CLASSROOM_INVENTORY_3,
    BEHAVIOUR_CLASSROOM_INVENTORY_4,
    BEHAVIOUR_CLASSROOM_INVENTORY_5,
    BEHAVIOUR_CLASSROOM_INVENTORY_GRADE,

    BEHAVIOUR_STUDENT_HYGIENE_1,
    BEHAVIOUR_STUDENT_HYGIENE_2,
    BEHAVIOUR_STUDENT_HYGIENE_3,
    BEHAVIOUR_STUDENT_HYGIENE_4,
    BEHAVIOUR_STUDENT_HYGIENE_5,
    BEHAVIOUR_STUDENT_HYGIENE_GRADE,

    BEHAVIOUR_STUDENT_BEHAVIOR_1,
    BEHAVIOUR_STUDENT_BEHAVIOR_2,
    BEHAVIOUR_STUDENT_BEHAVIOR_3,
    BEHAVIOUR_STUDENT_BEHAVIOR_4,
    BEHAVIOUR_STUDENT_BEHAVIOR_5,
    BEHAVIOUR_STUDENT_BEHAVIOR_GRADE,

    // გაცდენილი საათების ცხრილი:
    ABSENT_MONTHLY,

    // ტრანზიტული სკოლა:
    TRANSIT_SUMMARY_ASSIGMENT_1,
    TRANSIT_SUMMARY_ASSIGMENT_2,
    TRANSIT_SUMMARY_ASSIGMENT_RESTORATION,
    TRANSIT_SUMMARY_ASSIGMENT_MONTH,

    TRANSIT_SCHOOL_WORK_1,
    TRANSIT_SCHOOL_WORK_2,
    TRANSIT_SCHOOL_WORK_3,
    TRANSIT_SCHOOL_WORK_MONTH

}
