package mthiebi.sgs.models;

public enum Permissions {
	MANAGE_STUDENT,
	VIEW_STUDENT,
	MANAGE_ACADEMY_CLASS,
	VIEW_ACADEMY_CLASS,
	MANAGE_SUBJECT,
	VIEW_SUBJECT,
	EDIT_GRADES,
	ADD_OR_VIEW_GRADES,
	MANAGE_SYSTEM_USER

}
